<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="Bedroom" Id="{29421c85-e58d-4919-8d8f-6e5374a848f0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Bedroom
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Bedroom">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>