<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="Kitchen" Id="{73ae86c2-6ef1-4252-ba9b-bc7850429b37}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Kitchen
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Kitchen">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>