<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="AC" Id="{c4d831b3-90e1-4d32-9c0d-cbb508ea5eae}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AC
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="AC">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>