<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="Curtain" Id="{04557dba-7e8c-4135-9722-49b9f4a6c74b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Curtain
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Curtain">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>