<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="Fan" Id="{83141499-b7a6-42a6-9529-a95faf7cf666}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Fan
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Fan">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>