<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="Keypad" Id="{d9e2ad64-99a7-4404-80a9-c6bcdb8547c7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Keypad
VAR_INPUT
	keyIn : ARRAY[0..7] OF BOOL;
	KeypadType: INT; 		//	0: tap switch | 1: toggle switch
END_VAR
VAR_OUTPUT
	keyOut : ARRAY[0..7] OF BOOL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
CASE KeypadType OF
	0:
		
	1:
ELSE
	;
END_CASE






]]></ST>
    </Implementation>
    <LineIds Name="Keypad">
      <LineId Id="23" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="35" Count="1" />
      <LineId Id="33" Count="1" />
      <LineId Id="32" Count="0" />
      <LineId Id="17" Count="5" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>