<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="F_Scaling" Id="{b4f39728-83e7-4823-aac6-c98cad02cf6e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Scaling : REAL
VAR_INPUT
	Variable_In: REAL;		//	raw value of analog card
	ZeroIn: REAL;			//	min limit of analog card	
	ZeroOut: REAL;			//	max limit of analog card
	SpanIn: REAL;			//	Scalled min limit
	SpanOut: REAL;			//	Scalled max limit
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
	F_Scaling := (((SpanOut - SpanIn) / ZeroOut) * Variable_In) + SpanIn;

(*
The formula is:
Out := ((Variable_In - ZeroIn) / (SpanIn - ZeroIn)) * (SpanOut - ZeroOut) + ZeroOut.

Scaling:
(0..100) y = (900..1000)
(a..b) = (y..z)

Ans = (((z-y)/b) * variable) + y
x = (((1000 - 900)/100 ) * y) + 900
*)













]]></ST>
    </Implementation>
    <LineIds Name="F_Scaling">
      <LineId Id="3" Count="26" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>